fixup: Resolve build conflict between CCA and TIO
Fix kconfig circular dependency:

error: recursive dependency detected!
        symbol CRYPTO is selected by DM_CRYPT
        symbol DM_CRYPT depends on ENCRYPTED_KEYS
        symbol ENCRYPTED_KEYS depends on KEYS
        symbol KEYS is selected by ARM_CCA_HOST
        symbol ARM_CCA_HOST depends on PCI_TSM
        symbol PCI_TSM depends on ARCH_HAS_CC_PLATFORM
        symbol ARCH_HAS_CC_PLATFORM is selected by KVM_AMD_SEV
        symbol KVM_AMD_SEV depends on CRYPTO_DEV_SP_PSP
        symbol CRYPTO_DEV_SP_PSP depends on CRYPTO
Signed-off-by: Dan Williams <dan.j.williams@intel.com>